name: failed-only-or8n

on:
  push:

jobs:
  test-or8n:
    strategy:
      fail-fast: false
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:latest
    env:
      CURRENTS_PROJECT_ID: ghc2jY
      CURRENTS_RECORD_KEY: AcceNBS8GCEFdr4C
      CURRENTS_CI_BUILD_ID: ${{ github.repository }}-${{ github.run_id }}-${{ github.run_attempt }}
      CURRENTS_API_KEY: FlLFehSQxlNkBlh7C2X2E1RT43IiHNpF3vD578vVzQJUWHHuvsifXHkkQgTz3mtg
      CURRENTS_API_URL: https://cy-staging.currents.dev
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - run: |
          echo "$GITHUB_WORKSPACE"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: |
          npm install
      - name: Playwright Last Failed action
        id: last-failed-action
        uses: currents-dev/playwright-last-failed@v1
        with:
          or8n: true
          previous-ci-build-id: miguelangaranocurrents/nx-example-11977063661-1
          pw-output-dir: ./
      - name: Playwright Tests
        run: |
          echo "${{ toJson(steps.last-failed-action) }}"
          echo "${{ toJson(steps.last-failed-action.outputs) }}"
          COMMAND="npx nx run-many -t e2e --verbose --parallel=2 ${{ steps.last-failed-action.outputs.extra-pw-flags }} --last-failed"
          echo "Running command: $COMMAND"
          $COMMAND
